---
- name: Reset Hetzer host
  hosts: servers
  connection: local
  vars_files:
    - secrets.yml
  roles:
    - hetzner.rescue

- name: Install Hetzer host
  hosts: servers  
  vars_files:
    - secrets.yml
  roles:
    - hetzner.install
  tags:
    - install

- name: Install openvpn
  hosts: servers
  gather_facts: true
  vars:
    openvpn_client_register_dns: false
  roles:
    - { role: kyl191.openvpn, clients: [macbook] }
  tags:
    - install
    - openvpn

- name: Install fail2ban
  hosts: servers
  vars:
  roles:
    - robertdebock.fail2ban
  tags:
    - install
    - fail2ban

- name: Install Kubernetes
  hosts: servers
  vars:
    kubernetes_allow_pods_on_master: True
    kubernetes_pod_network_cidr: 10.244.0.0/16
    kubernetes_version: '1.13'
    kubernetes_version_rhel_package: '1.13.3'
    swap_file_state: absent
  roles:
    - geerlingguy.docker
    - geerlingguy.swap
    - geerlingguy.kubernetes
  tags:
    - install
    - k8s

- name: Install Kubernetes apps
  hosts: servers
  roles:
    - andrewrothstein.kubernetes-helm
  tags:
    - install
    - k8s
    - k8s-tools