---
- name: Reset Hetzer host
  hosts: servers
  connection: local
  vars_files:
    - secrets.yml
  roles:
    - hetzner.rescue

- name: Install Hetzer host
  hosts: servers  
  vars_files:
    - secrets.yml
  roles:
    - hetzner.install
  tags:
    - install

- name: Install openvpn
  hosts: servers
  gather_facts: true
  vars:
    openvpn_client_register_dns: false
  roles:
    - { role: kyl191.openvpn, clients: [macbook] }
  tags:
    - install
    - openvpn